import sys, pathlib, glob
from playwright.sync_api import sync_playwright

sp = pathlib.Path.cwd() / 'out' / 'e2e'
sp.mkdir(parents=True, exist_ok=True)
# 사용: python e2e_test.py [데모 html]. 없으면 실행 폴더 out/ 의 가장 최근 데모를 연다.
f = sys.argv[1] if len(sys.argv) > 1 else sorted(glob.glob(str(pathlib.Path.cwd() / 'out' / '*화면 데모_v*.html')))[-1]
url = pathlib.Path(f).resolve().as_uri()
res = []


def ok(name, cond):
    res.append((name, bool(cond)))
    print('PASS' if cond else 'FAIL', name)


with sync_playwright() as p:
    b = p.chromium.launch()
    pg = b.new_page(viewport={'width': 1500, 'height': 1000})
    errs = []
    pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto(url)
    pg.wait_for_timeout(300)
    D = lambda: pg.locator('#device')
    pg.click('[data-act=login]')
    ok('빈 로그인 오류 표시', '입력하세요' in D().inner_text())
    pg.fill('#lid', 'minsu'); pg.fill('#lpw', 'pw'); pg.click('[data-act=login]')
    ok('이메일 형식 검사', '이메일 형식' in D().inner_text())
    pg.click('[data-arg=A-03]'); pg.fill('#remail', 'minsu@example.com'); pg.click('[data-act=sendreset]')
    ok('비밀번호 찾기 메일 안내', '메일을 보냈어요' in D().inner_text())
    pg.click('[data-arg=A-04]'); pg.fill('#npw', '12345678'); pg.fill('#npw2', '12345678'); pg.click('[data-act=savepw]'); pg.wait_for_timeout(200)
    ok('새 비밀번호 뒤 로그인 화면, 이메일 채움', pg.input_value('#lid') == 'minsu@example.com')
    pg.fill('#lpw', 'pw'); pg.click('[data-act=login]'); pg.wait_for_timeout(200)
    ok('로그인 후 홈', '다음 모임' in D().inner_text())
    pg.click('.card.todo')
    ok('할 일 카드로 C-03', '1/2' in D().inner_text())
    pg.click('[data-act=cycle][data-arg="1"]'); pg.click('[data-act=cycle][data-arg="3"]'); pg.click('[data-act=cycle][data-arg="3"]')
    ok('안 됨, 바뀔 수도 표시', pg.locator('.day.no').count() == 1 and pg.locator('.day.maybe').count() == 1)
    pg.click('[data-act=calview][data-arg=month]')
    ok('월간 보기 4주', pg.locator('.cal .day').count() == 28)
    pg.click('[data-act=step2]')
    ok('2단계 이동, 안 되는 날 제외', '2/2' in D().inner_text() and pg.locator('.trow').count() == 6)
    pg.click('[data-act=submitavail]'); pg.wait_for_timeout(2200)
    ok('전원 제출 뒤 투표 단계', pg.eval_on_selector('#stagesel', 'e=>e.value') == 'vote')
    ok('디스코드 패널에 후보 공지', '후보 시간이 나왔습니다' in pg.inner_text('#dcfeed'))
    pg.click('button[data-arg=C-05][data-d="4"]')
    n = pg.locator('.cand').count()
    ok(f'후보 {n}개 표시', n > 0)
    ok('2순위 후보 표시', '2순위' in D().inner_text())
    pg.locator('.cand').first.click(); pg.click('[data-act=castvote]'); pg.wait_for_timeout(1800)
    ok('투표 뒤 자동 확정', '자동 공지됨' in D().inner_text())
    ok('회원에게 변경 버튼 없음', pg.locator('[data-arg=change]').count() == 0)
    pg.select_option('#rolesel', '홍길동'); pg.wait_for_timeout(100)
    pg.click('[data-arg=change]')
    ok('변경 팝업', '일정을 바꿀까요' in D().inner_text())
    pg.click('[data-act=dochange]'); pg.wait_for_timeout(200)
    ok('변경 뒤 재투표 화면', '다시 투표해요' in D().inner_text())
    ok('변경 알림 디스코드', '다시 투표해 주세요' in pg.inner_text('#dcfeed'))
    pg.click('.tabs button:nth-child(3)'); pg.click('[data-act=newnotice]')
    pg.fill('[data-field=발표자]', '이영희'); pg.fill('[data-field=주제]', '시험 주제')
    ok('미리보기 반영', '시험 주제' in pg.inner_text('#device .emb'))
    pg.click('[data-act=draft]')
    ok('임시저장 목록', D().locator('.badge.draft').count() >= 2)
    pg.click('[data-act=newnotice]'); pg.fill('[data-field=주제]', '발송 시험')
    pg.click('[data-act=modal][data-arg=send]'); pg.click('[data-act=send]'); pg.wait_for_timeout(1300)
    ok('발송 후 디스코드 도착', '발송 시험' in pg.inner_text('#dcfeed'))
    pg.click('[data-act=resend]'); pg.wait_for_timeout(1200)
    ok('실패 공지 다시 보내기', D().locator('.badge.no').count() == 0)
    pg.click('[data-arg=D-03]'); pg.fill('#tbody', '{날짜} 에 {새빈칸}'); pg.wait_for_timeout(800)
    ok('템플릿 빈칸 인식', '새빈칸' in D().inner_text())
    pg.click('#devseg button[data-arg=pc]'); pg.click('.snav [data-arg=E-02]'); pg.click('[data-act=refresh]')
    ok('새로 고침 새 파일', '새 파일' in D().inner_text())
    pg.locator('input[data-act=pick]:not([disabled])').first.check(); pg.click('[data-arg=upconfirm]')
    ok('업로드 확인 팝업', '이 파일을 올릴까요' in D().inner_text())
    pg.click('[data-act=doupload]'); pg.wait_for_timeout(5500)
    ok('업로드 완료', '1/1 완료' in D().inner_text())
    pg.click('[data-act=uploadnotice]'); pg.click('.snav [data-arg=E-01]')
    ok('자료실에 올린 파일', '2026-09-28 20-02-40.mp4' in D().inner_text())
    pg.click('#devseg button[data-arg=web]')
    ok('PC 앱에서 웹으로 바꿔도 같은 화면', '자료실' in D().inner_text())
    pg.select_option('#rolesel', '김철수'); pg.evaluate("ACT.go('G-01')"); pg.wait_for_timeout(100)
    ok('회원은 관리자 권한 없음', '권한이 없어요' in D().inner_text())
    ok('회원 메뉴에 관리자 없음', pg.locator('.snav [data-arg=G-01]').count() == 0)
    pg.select_option('#rolesel', '홍길동'); pg.evaluate("ACT.go('G-01')"); pg.wait_for_timeout(100)
    ok('홍길동는 관리자이면서 팀장', '관리자, 팀장' in D().inner_text())
    ok('자기 관리자 권한은 못 풂', pg.locator('input[data-act=setadmin]').first.is_disabled())
    pg.locator('input[data-act=setadmin]').nth(1).click(); pg.wait_for_timeout(100)
    ok('다른 회원에게 관리자 추가', '관리자 2명' in D().inner_text())
    pg.locator('select[data-act=setrole]').nth(2).select_option('회원'); pg.wait_for_timeout(100)
    ok('부팀장 0명이면 저장 막힘', pg.locator('[data-act=saveroles]').is_disabled())
    pg.click('.admtabs button:has-text("대상별 공지")')
    ok('대상별 공지 화면', '대상별 공지' in D().inner_text())
    pg.click('[data-act=admtarget][data-arg=팀장]')
    ok('팀장 대상은 운영진 방', '# 운영진' in D().inner_text())
    pg.click('#desctog'); pg.wait_for_timeout(300)
    ok('설명 보기 번호 표시', pg.locator('#device .mk').count() >= 3)
    pg.click('#devseg button[data-arg=mob]'); pg.click('.tabs button:nth-child(5)')
    pg.click('[data-arg=logout]'); pg.click('[data-act=logout]')
    ok('로그아웃 뒤 로그인 화면', pg.locator('[data-act=login]').count() == 1 and pg.locator('.tabs').count() == 0)
    pg.set_viewport_size({'width': 420, 'height': 900}); pg.wait_for_timeout(200)
    ok('좁은 화면 가로 스크롤 없음', pg.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
    pg.screenshot(path=str(sp / 'narrow.png'))
    pg.set_viewport_size({'width': 1500, 'height': 1000}); pg.goto(url + '#C-03'); pg.wait_for_timeout(300)
    pg.screenshot(path=str(sp / 'full.png'))
    for dev in ['mob', 'pc', 'web']:
        bad = []
        for sid in pg.evaluate('SPEC.screens.map(s => s.id)'):
            pg.goto(url + f'?dev={dev}&t={sid}#{sid}'); pg.wait_for_timeout(120)
            if len(D().inner_text()) < 30: bad.append(sid)
        ok(f'{dev}: 모든 화면이 열림 {bad or ""}', not bad)
    ok('스크립트 오류 없음', not errs)
    print(errs[:3])
    b.close()
print(sum(1 for _, c in res if c), '/', len(res))
